/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chat Conversations */
        get: operations["list_chat_conversations_api_chat_conversations_get"];
        put?: never;
        /** Create Chat Conversation */
        post: operations["create_chat_conversation_api_chat_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Chat Conversation */
        get: operations["load_chat_conversation_api_chat_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continue Chat Conversation */
        post: operations["continue_chat_conversation_api_chat_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Chat Run */
        post: operations["start_chat_run_api_chat_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat Run */
        get: operations["get_chat_run_api_chat_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Chat Run Events */
        get: operations["stream_chat_run_events_api_chat_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Documents */
        get: operations["api_documents_api_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Document Endpoint */
        post: operations["delete_document_endpoint_api_documents_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/delete-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Documents By Id Endpoint */
        post: operations["delete_documents_by_id_endpoint_api_documents_delete_by_id_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/delete-selected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Selected Documents Endpoint */
        post: operations["delete_selected_documents_endpoint_api_documents_delete_selected_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Document Process */
        get: operations["api_document_process_api_documents_process_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Document */
        get: operations["api_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Document Chunks */
        get: operations["api_document_chunks_api_documents__document_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/index-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Document Index Points */
        get: operations["api_document_index_points_api_documents__document_id__index_points_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/markdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Document Markdown */
        get: operations["api_document_markdown_api_documents__document_id__markdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Ingest */
        post: operations["start_ingest_api_jobs_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pipeline Runs */
        get: operations["list_pipeline_runs_api_pipeline_runs_get"];
        put?: never;
        /** Start Pipeline Run */
        post: operations["start_pipeline_run_api_pipeline_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pipeline Run */
        get: operations["get_pipeline_run_api_pipeline_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline-runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Pipeline Events */
        get: operations["stream_pipeline_events_api_pipeline_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/chat-model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat Model Setting */
        get: operations["get_chat_model_setting_api_settings_chat_model_get"];
        /** Update Chat Model Setting */
        put: operations["update_chat_model_setting_api_settings_chat_model_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Status */
        get: operations["api_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Overview */
        get: operations["workspace_overview_api_workspace_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application Route */
        get: operations["application_route_assistant_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application Route */
        get: operations["application_route_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legacy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Dashboard */
        get: operations["legacy_dashboard_legacy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login Page */
        get: operations["login_page_login_get"];
        put?: never;
        /** Login */
        post: operations["login_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application Route */
        get: operations["application_route_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application Route */
        get: operations["application_route_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application Route */
        get: operations["application_route_retrieval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_delete_document_endpoint_api_documents_delete_post */
        Body_delete_document_endpoint_api_documents_delete_post: {
            /**
             * Csrf Token
             * @default
             */
            csrf_token: string;
            /**
             * Relative Raw Path
             * @default
             */
            relative_raw_path: string;
        };
        /** Body_login_login_post */
        Body_login_login_post: {
            /**
             * Password
             * @default
             */
            password: string;
            /**
             * Username
             * @default
             */
            username: string;
        };
        /** Body_logout_logout_post */
        Body_logout_logout_post: {
            /**
             * Csrf Token
             * @default
             */
            csrf_token: string;
        };
        /** Body_upload_document_api_documents_upload_post */
        Body_upload_document_api_documents_upload_post: {
            /**
             * Csrf Token
             * @default
             */
            csrf_token: string;
            /** File */
            file: string[];
        };
        /** ChatMessageDto */
        ChatMessageDto: {
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Insufficient Context */
            insufficient_context: boolean;
            /** Role */
            role: string;
            /** Sequence */
            sequence: number;
            /** Sources */
            sources: components["schemas"]["ChatSourceDto"][];
            /** Trace Events */
            trace_events: components["schemas"]["ChatTraceEventDto"][];
        };
        /** ChatModelOptionDto */
        ChatModelOptionDto: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Model Id */
            model_id: string;
        };
        /** ChatModelSelectionRequest */
        ChatModelSelectionRequest: {
            /** Key */
            key: string;
        };
        /** ChatModelSettingsResponse */
        ChatModelSettingsResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Options */
            options: components["schemas"]["ChatModelOptionDto"][];
            /** Selected */
            selected: string;
        };
        /** ChatRunCreateRequest */
        ChatRunCreateRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Limit
             * @default 5
             */
            limit: number;
            /** Question */
            question: string;
            /** Specialist */
            specialist?: string | null;
        };
        /** ChatRunDto */
        ChatRunDto: {
            conversation: components["schemas"]["ConversationDto"] | null;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Question */
            question: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Trace Events */
            trace_events: components["schemas"]["ChatTraceEventDto"][];
        };
        /** ChatRunResponse */
        ChatRunResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            run: components["schemas"]["ChatRunDto"];
        };
        /** ChatRunStartResponse */
        ChatRunStartResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            run: components["schemas"]["ChatRunStartedDto"];
        };
        /** ChatRunStartedDto */
        ChatRunStartedDto: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** ChatSourceDto */
        ChatSourceDto: {
            /** Char End */
            char_end: number | null;
            /** Char Start */
            char_start: number | null;
            /** Chunk Index */
            chunk_index: number | null;
            /** Content Hash */
            content_hash: string | null;
            /** Document Id */
            document_id: string | null;
            /** Document Name */
            document_name: string | null;
            /** Excerpt */
            excerpt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Qdrant Point Id */
            qdrant_point_id: string | null;
            /** Relative Raw Path */
            relative_raw_path: string | null;
            /** Retrieval Query */
            retrieval_query: string | null;
            /** Score */
            score: number | null;
            /** Source */
            source: string | null;
            /** Source Id */
            source_id: string;
            /**
             * Used
             * @default false
             */
            used: boolean;
        };
        /** ChatTraceEventDto */
        ChatTraceEventDto: {
            /** Agent Name */
            agent_name: string | null;
            /** Created At */
            created_at?: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Event Type */
            event_type: string;
            /** Id */
            id?: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Phase */
            phase: string;
            /** Sequence */
            sequence: number;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Tool Name */
            tool_name: string | null;
        };
        /** ChunkDto */
        ChunkDto: {
            /** Char End */
            char_end: number | null;
            /** Char Start */
            char_start: number | null;
            /** Characters */
            characters: number;
            /** Content */
            content: string;
            /** Index */
            index: number;
        };
        /** ConversationDto */
        ConversationDto: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Messages */
            messages: components["schemas"]["ChatMessageDto"][];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ConversationSummaryDto */
        ConversationSummaryDto: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Message Count */
            message_count: number;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DashboardStatusDto */
        DashboardStatusDto: {
            /** Document Count */
            document_count: number;
            /** Last Processed At */
            last_processed_at: string | null;
            /** Parsed Markdown Count */
            parsed_markdown_count: number;
            qdrant: components["schemas"]["QdrantStatusDto"];
            /** Raw Pdf Count */
            raw_pdf_count: number;
        };
        /** DocumentChunksResponse */
        DocumentChunksResponse: {
            /** Chunks */
            chunks: components["schemas"]["ChunkDto"][];
            document: components["schemas"]["DocumentDto"];
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** DocumentDeleteRequest */
        DocumentDeleteRequest: {
            /** Document Ids */
            document_ids: string[];
        };
        /** DocumentDto */
        DocumentDto: {
            /** Byte Size */
            byte_size: number | null;
            /** Content Hash */
            content_hash: string | null;
            /** Created At */
            created_at?: string | null;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string | null;
            /** Indexed */
            indexed: boolean | null;
            /** Indexed At */
            indexed_at?: string | null;
            /** Original Filename */
            original_filename: string;
            /** Parsed Exists */
            parsed_exists: boolean;
            /** Parsed Markdown Path */
            parsed_markdown_path: string | null;
            /** Processed At */
            processed_at: string | null;
            /** Processing Error */
            processing_error?: string | null;
            /** Raw Exists */
            raw_exists: boolean;
            /** Relative Raw Path */
            relative_raw_path: string;
            /** Status */
            status: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** DocumentIndexResponse */
        DocumentIndexResponse: {
            document: components["schemas"]["DocumentDto"];
            index: components["schemas"]["IndexPreviewDto"];
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** DocumentMarkdownResponse */
        DocumentMarkdownResponse: {
            document: components["schemas"]["DocumentDto"];
            /** Markdown */
            markdown: string | null;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** DocumentPageResponse */
        DocumentPageResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentDto"][];
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
            /** Qdrant Error */
            qdrant_error: string | null;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /** DocumentResponse */
        DocumentResponse: {
            document: components["schemas"]["DocumentDto"];
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            /** Failed Count */
            failed_count: number;
            /** Ok */
            ok: boolean;
            /** Results */
            results: components["schemas"]["UploadResultDto"][];
            /** Uploaded Count */
            uploaded_count: number;
            /** Uploads */
            uploads: {
                [key: string]: unknown;
            }[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexPreviewDto */
        IndexPreviewDto: {
            /** Available */
            available: boolean;
            /** Collection Exists */
            collection_exists: boolean;
            /** Collection Name */
            collection_name: string | null;
            /** Error */
            error?: string | null;
            /** Points */
            points?: {
                [key: string]: unknown;
            }[];
            /** Preview Limit */
            preview_limit: number;
            /**
             * Shown Points
             * @default 0
             */
            shown_points: number;
        };
        /** PipelineDocumentDto */
        PipelineDocumentDto: {
            /** Current Step */
            current_step: string | null;
            /** Document Id */
            document_id: string | null;
            /** Document Name */
            document_name: string;
            /** Error */
            error: string | null;
            /** Position */
            position: number;
            /** Relative Raw Path */
            relative_raw_path: string;
            /** Status */
            status: string;
        };
        /** PipelineEventDto */
        PipelineEventDto: {
            /** Counters */
            counters: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Sequence */
            sequence: number;
            /** Status */
            status: string;
            /** Step */
            step: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** PipelineRunCreateRequest */
        PipelineRunCreateRequest: {
            /** Document Ids */
            document_ids?: string[];
        };
        /** PipelineRunDto */
        PipelineRunDto: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Documents */
            documents: components["schemas"]["PipelineDocumentDto"][];
            /** Error */
            error: string | null;
            /** Events */
            events: components["schemas"]["PipelineEventDto"][];
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Summary */
            summary: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PipelineRunListResponse */
        PipelineRunListResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Runs */
            runs: components["schemas"]["PipelineRunDto"][];
        };
        /** PipelineRunResponse */
        PipelineRunResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            run: components["schemas"]["PipelineRunDto"];
        };
        /** PostgresStatusDto */
        PostgresStatusDto: {
            /** Available */
            available: boolean;
            /** Error */
            error: string | null;
        };
        /** QdrantStatusDto */
        QdrantStatusDto: {
            /** Available */
            available: boolean;
            /** Collection Exists */
            collection_exists: boolean;
            /** Collection Name */
            collection_name: string | null;
            /** Error */
            error: string | null;
            /** Points Count */
            points_count: number | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /** Query */
            query: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Error */
            error?: string | null;
            /** Limit */
            limit: number;
            /** Ok */
            ok: boolean;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchResultDto"][];
        };
        /** SearchResultDto */
        SearchResultDto: {
            /** Char End */
            char_end: number | null;
            /** Char Start */
            char_start: number | null;
            /** Chunk Index */
            chunk_index: number | null;
            /** Content Hash */
            content_hash: string | null;
            /** Document Id */
            document_id: string | null;
            /** Document Name */
            document_name: string | null;
            /** Excerpt */
            excerpt: string;
            /** Qdrant Point Id */
            qdrant_point_id: string | null;
            /** Relative Raw Path */
            relative_raw_path: string | null;
            /** Score */
            score: number | null;
            /** Source */
            source: string | null;
        };
        /** UploadResultDto */
        UploadResultDto: {
            /** Bytes */
            bytes?: number | null;
            /** Document Id */
            document_id?: string | null;
            /** Error */
            error?: string | null;
            /** File Name */
            file_name: string;
            /** Relative Raw Path */
            relative_raw_path?: string | null;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceOverviewResponse */
        WorkspaceOverviewResponse: {
            latest_conversation: components["schemas"]["ConversationSummaryDto"] | null;
            latest_pipeline_run: components["schemas"]["PipelineRunDto"] | null;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            postgres: components["schemas"]["PostgresStatusDto"];
            status: components["schemas"]["DashboardStatusDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_chat_conversations_api_chat_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_chat_conversation_api_chat_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    load_chat_conversation_api_chat_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_chat_conversation_api_chat_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_chat_run_api_chat_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRunStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_run_api_chat_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_chat_run_events_api_chat_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_documents_api_documents_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                query?: string | null;
                status?: string | null;
                sort?: string;
                direction?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_endpoint_api_documents_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_delete_document_endpoint_api_documents_delete_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_documents_by_id_endpoint_api_documents_delete_by_id_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_selected_documents_endpoint_api_documents_delete_selected_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_document_process_api_documents_process_get: {
        parameters: {
            query: {
                relative_raw_path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_document_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_document_chunks_api_documents__document_id__chunks_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentChunksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_document_index_points_api_documents__document_id__index_points_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentIndexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_document_markdown_api_documents__document_id__markdown_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentMarkdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    start_ingest_api_jobs_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pipeline_runs_api_pipeline_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_pipeline_run_api_pipeline_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_run_api_pipeline_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_pipeline_events_api_pipeline_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_model_setting_api_settings_chat_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatModelSettingsResponse"];
                };
            };
        };
    };
    update_chat_model_setting_api_settings_chat_model_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatModelSelectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatModelSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    workspace_overview_api_workspace_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOverviewResponse"];
                };
            };
        };
    };
    application_route_assistant_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    application_route_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    legacy_dashboard_legacy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    login_page_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    login_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_logout_logout_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    application_route_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    application_route_pipeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    application_route_retrieval_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
